### ISSUE TITLE
JKU provider error: coupling map

### ISSUE THREAD

**Issue by sassan72** [qiskit-community/qiskit-jku-provider#73]
i tried to run this example. i got this error.

# Import tools
from qiskit import *
from qiskit_jku_provider import JKUProvider

# Create an instance of the JKU Provider
JKU = JKUProvider()

# Create a quantum circuit
qr = QuantumRegister(2)
cr = ClassicalRegister(2)
qc = QuantumCircuit(qr, cr)

# Add quantum gates
qc.h(qr[0])
qc.cx(qr[0], qr[1])
qc.measure(qr, cr)

# Get the JKU backend from the JKU provider
jku_backend = JKU.get_backend('qasm_simulator')

# Simulate the circuit with the JKU Simulator
job = execute(qc, backend=jku_backend)

# Retrieve and display the results
result = job.result()
print(result.get_counts(qc))

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-cfbd37616958> in <module>
      4 
      5 # Create an instance of the JKU Provider
----> 6 JKU = JKUProvider()
      7 
      8 # Create a quantum circuit

~/anaconda3/lib/python3.7/site-packages/qiskit_jku_provider/jkuprovider.py in __init__(self, *args, **kwargs)
     23 
     24         # Populate the list of local JKU backends.
---> 25         self.backends_list = {'qasm_simulator': QasmSimulator(provider=self)}
     26 
     27     def get_backend(self, name, **kwargs):

~/anaconda3/lib/python3.7/site-packages/qiskit_jku_provider/qasm_simulator_jku.py in __init__(self, configuration, provider, silent)
    316         """
    317         super().__init__(configuration=(configuration or
--> 318                                         BackendConfiguration.from_dict(self.DEFAULT_CONFIGURATION)),
    319                          provider=provider)
    320 

~/anaconda3/lib/python3.7/site-packages/qiskit/providers/models/backendconfiguration.py in from_dict(cls, data)
    343         gates = [GateConfig.from_dict(x) for x in in_data.pop('gates')]
    344         in_data['gates'] = gates
--> 345         return cls(**in_data)
    346 
    347     def to_dict(self):

TypeError: __init__() missing 1 required positional argument: 'coupling_map'

**Comment by hillmich** [comment]
Hi,

you should be able to make it work by adding
```python
'coupling_map': None,
```
to the `DEFAULT_CONFIGURATION` of the `QasmSimulator` class in the file `qasm_simulator_jku.py`. 
You'll  have to find where this is installed though.

**Comment by sassan72** [comment]
thanks Stefan. it works.

**Comment by EziOzoani** [comment]
Hi, 
I'm getting a similar error, however it's when I'm trying to create an instance of the of the JKU Provider
I'm using google colab due to Jyputer Notebook not recognising the JKU qiskit import. So I can't access the DEFAULT_CONFIGURATION of the QasmSimulator class in the file qasm_simulator_jku.py, like you explained above 

I get this return:

TypeError                                 Traceback (most recent call last)
<ipython-input-37-eeb547ba2cad> in <module>()
      1 # Create an instance of the JKU Provider
----> 2 JKU = JKUProvider()

2 frames
/usr/local/lib/python3.7/dist-packages/qiskit/providers/models/backendconfiguration.py in from_dict(cls, data)
    328         gates = [GateConfig.from_dict(x) for x in in_data.pop('gates')]
    329         in_data['gates'] = gates
--> 330         return cls('coupling_map': None)#**in_data)
    331 
    332     def to_dict(self):

TypeError: __init__() missing 1 required positional argument: 'coupling_map'

**Comment by sassan72** [comment]
this link https://github.com/qiskit-community/qiskit-jku-provider/issues/73#issuecomment-760078551 solved my problem. add 'coupling_map': None, to DEFAULT_CONFIGURATION of the QasmSimulator class in the file qasm_simulator_jku.py. As Stefan wrote in above comment.

**Comment by EziOzoani** [comment]
Hi, this worked perfectly.
I ran the simulation section to execute the job and got this error

QiskitError: "Cannot unroll the circuit to the given basis, ['u0', 'u1', 'u2', 'u3', 'cx', 'x', 'y', 'z', 'h', 's', 't', 'snapshot']. Instruction id not found in equivalence library and no rule found to expand."

**Comment by sassan72** [comment]
Do you have your input? i can check it for you.

**Comment by EziOzoani** [comment]
It was when I ran 

job = execute(qc, backend=jku_backend)

Or do you need the whole circuit ?

**Comment by sassan72** [comment]
If I have the whole circuit, I will tell how to fix it? Actually, I worked with this simulator.

**Comment by sassan72** [comment]
You need to install qiskit, as well. If you look at the error, it is qiskit error, not jku.

**Comment by EziOzoani** [comment]
Hi, I put in a comment on a closed issue similar on the qiskit git. 
The [response]([url](url)) is below 

![Screenshot 2021-03-25 at 02 57 16](https://user-images.githubusercontent.com/25269943/112412255-21c09c00-8d16-11eb-898a-2def126b06ae.png)
